In [1]:
import numpy as np 

In [3]:
arr = np.array([1,2,3,4,5,6])
result = arr ** 2
result 

array([ 1,  4,  9, 16, 25, 36])

In [5]:
result + 10

array([11, 14, 19, 26, 35, 46])

In [13]:
arr2 = np.array([11, 14, 19, 26, 35, 46])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
reult = arr + arr2

In [19]:
reult

array([12, 16, 22, 30, 40, 52])

In [21]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr1d = np.array([1,2,3])
r = arr2d + arr1d

In [23]:
r

array([[2, 4, 6],
       [5, 7, 9]])

In [38]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

In [40]:
mean = data.mean(axis = 0)
std = data.std(axis=0)

In [44]:
std

array([7.07106781, 7.07106781, 7.07106781])

In [46]:
normalized_data = (data - mean) / std
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])