In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros_like((3,3))

array([0, 0])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [7]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [8]:
np.arange(1,100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [9]:
np.linspace(0,10000,10)

array([    0.        ,  1111.11111111,  2222.22222222,  3333.33333333,
        4444.44444444,  5555.55555556,  6666.66666667,  7777.77777778,
        8888.88888889, 10000.        ])

In [10]:
myArr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])

In [11]:
myArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [12]:
print("Shape: ", myArr.shape)

Shape:  (4, 3)


In [13]:
print("Size: ", myArr.size)

Size:  12


In [14]:
print("Dimensions: ", myArr.ndim)

Dimensions:  2


In [15]:
print("Data type: ", myArr.dtype)

Data type:  int32


In [16]:
myArr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]], dtype = "int64")
myArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]], dtype=int64)

In [17]:
myArr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]], dtype = "float64")
myArr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [0., 1., 2.]])

In [18]:
reshaped = myArr.reshape((3,4))
reshaped

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [9., 0., 1., 2.]])

In [19]:
myArr.flatten()

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1., 2.])

In [42]:
import random

matArr = np.random.randint(10, size=(3, 3))
matArr

array([[9, 7, 9],
       [0, 6, 2],
       [9, 6, 5]])

In [44]:
floatArr = np.array([1.1,2.2,3.3])
floatArr

array([1.1, 2.2, 3.3])

In [49]:
floatArr = np.array([1.1,2.2,3.3], dtype = "int32")

In [51]:
floatArr

array([1, 2, 3])

In [78]:
listLike = np.array([1, 2, 1.5, False], dtype = "int64")

In [67]:
listLike

array(['1', '2', '1.5', 'False'], dtype='<U6')

In [63]:
strList = np.array(["Ab vai"])
print("Data type: ", strList.dtype)

Data type:  <U6
