In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [4]:
flat = arr.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [5]:
flat[0]

1

In [6]:
flat[1:3]

array([2, 3])

In [7]:
flat[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [8]:
flat[:5]

array([1, 2, 3, 4, 5])

In [9]:
flat[3:]

array([4, 5, 6, 7, 8, 9, 0, 1, 2])

In [10]:
flat[0:13]

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [11]:
a = flat[:6]

In [12]:
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a[1] = 44

In [14]:
a

array([ 1, 44,  3,  4,  5,  6])

In [15]:
flat

array([ 1, 44,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2])

In [16]:
list1 = [3,  4,  5,  6,  7,  8,  9,  0,  1,  2]
list1

[3, 4, 5, 6, 7, 8, 9, 0, 1, 2]

In [17]:
list2 = list1[0:5]
list2


[3, 4, 5, 6, 7]

In [18]:
list2[1] = 10
list2


[3, 10, 5, 6, 7]

In [19]:

list1

[3, 4, 5, 6, 7, 8, 9, 0, 1, 2]

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [21]:
flat

array([ 1, 44,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2])

In [22]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
flat = arr.flatten()
a = flat[:6]
a[1] = 44
flat

array([ 1, 44,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2])

In [23]:
arr[[1, 2, 3]]

array([[4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [24]:
arr = np.array([ 1, 44,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2])

In [25]:
arr[[1, 2, 3]]

array([44,  3,  4])

In [26]:
arr[arr>6]

array([44,  7,  8,  9])

In [27]:
newNum = np.array([1,2,3,4,5,6])

In [58]:
idx = [x for x in range(1,6) if x%2 != 0]
idx

[1, 3, 5]

In [60]:
print(newNum[idx])

[2 4 6]


In [62]:
newMatrix = np.array([1,2,3,4,5,6,7,8,9])

In [66]:
reshaped = newMatrix.reshape((3,3))
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
a= np.eye(3)
# a.shape
b = a.reshape(3,3,1)
b


array([[[1.],
        [0.],
        [0.]],

       [[0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [1.]]])

In [76]:
ab = np.eye(4)
ab

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
import random

matArr = np.random.randint(100, size=(4, 4, 3))
matArr

array([[[68, 63, 68],
        [73, 43,  3],
        [10, 72, 46],
        [15, 83, 46]],

       [[90,  9, 36],
        [30, 40, 42],
        [98,  7, 46],
        [22, 36, 39]],

       [[43, 49, 95],
        [94, 46, 34],
        [29, 78, 98],
        [99, 21, 32]],

       [[47, 36, 86],
        [69, 20,  6],
        [85, 63, 61],
        [74, 35, 98]]])

In [88]:
newMatt = [matArr > 50]

In [90]:
newMatt

[array([[[ True,  True,  True],
         [ True, False, False],
         [False,  True, False],
         [False,  True, False]],
 
        [[ True, False, False],
         [False, False, False],
         [ True, False, False],
         [False, False, False]],
 
        [[False, False,  True],
         [ True, False, False],
         [False,  True,  True],
         [ True, False, False]],
 
        [[False, False,  True],
         [ True, False, False],
         [ True,  True,  True],
         [ True, False,  True]]])]