In [1]:
import numpy as np

In [32]:
arr = np.array([3,4,5,2,1,1])

In [5]:
np.mean(arr)

3.0

In [7]:
np.min(arr)

1

In [9]:
np.max(arr)

5

In [13]:
np.std(arr)

1.4142135623730951

In [15]:
np.var(arr)

2.0

In [17]:
np.prod(arr)

120

In [19]:
np.sum(arr)

15

In [25]:
np.argmin(arr)

4

In [27]:
np.argmax(arr)

2

In [34]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [36]:
np.cumsum(arr)

array([ 3,  7, 12, 14, 15, 16])

In [38]:
np.exp(arr)

array([ 20.08553692,  54.59815003, 148.4131591 ,   7.3890561 ,
         2.71828183,   2.71828183])