In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr[1]

array([4, 5, 6])

In [3]:
arr[0][1]

2

In [34]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [5]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [6]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,22,33]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 22, 33]]])

In [7]:
arr3D.shape

(2, 2, 3)

In [8]:
arr3D.ndim

3

In [9]:
arr3D[0,1,2]

6

In [10]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [11]:
arr[:,0]

array([1, 4, 7])

In [12]:
arr3D[0,0,:]

array([1, 2, 3])

In [13]:
arr3D[0,0,:] = 0

In [14]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 22, 33]]])