In [1]:
import numpy as np

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(arr.shape)

(2, 3, 3)


In [7]:
print(arr[0, 1, 2])

6


In [9]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
arr[0, : , :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[0, 0:1, :]

array([[1, 2, 3]])

In [17]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [19]:
arr[[0,1],:,:]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
arr2 = np.arange(15).reshape((3,5))
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
arr2.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [25]:
np.dot(arr2.T,arr2)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [27]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr2.swapaxes(0,1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [33]:
sample = np.random.standard_normal(size=(4,4))

In [35]:
sample

array([[ 1.59448263, -0.12031425, -1.69149555, -1.71227431],
       [-0.01017808, -0.87137061,  0.66537687, -1.06995762],
       [ 1.23784053, -1.27642721,  1.25363903,  1.28884191],
       [ 0.48950801,  2.75525059, -0.01552712,  0.74234709]])

In [37]:
from random import normalvariate

In [39]:
n = 1_000_000

In [41]:
%timeit sample = [normalvariate(0,1) for _ in range(n)]

944 ms ± 13.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
%timeit np.random.standard_normal(n)

34.1 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [50]:
st = np.random.standard_normal(7)*5
st

array([ 3.89666169, -7.38255939,  0.92818632,  1.27953721,  4.22505232,
        1.13182204,  1.08824557])

In [52]:
remainder, whole_part = np.modf(st)


In [54]:
remainder

array([ 0.89666169, -0.38255939,  0.92818632,  0.27953721,  0.22505232,
        0.13182204,  0.08824557])

In [56]:
whole_part

array([ 3., -7.,  0.,  1.,  4.,  1.,  1.])