In [1]:
import numpy as np

In [5]:
n = np.empty((5,4,3))

In [13]:
np.asarray([1,2])

array([1, 2])

In [19]:
li = [1,2,3,4]
li2 = np.asarray(li)

In [21]:
np.zeros_like(li2)

array([0, 0, 0, 0])

In [37]:
np.eye(3,4, dtype=np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [52]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])